In [1]:
# Import datasets, classifiers and performance metrics
from sklearn import datasets, svm, metrics

import numpy as np

In [2]:
digits = datasets.load_digits()

In [3]:
from collections import Counter
print(digits.images[0].shape)
Counter(digits.target)

(8, 8)


Counter({0: 178,
         1: 182,
         2: 177,
         3: 183,
         4: 181,
         5: 182,
         6: 181,
         7: 179,
         8: 174,
         9: 180})

In [6]:
print(digits.images[802])
print(digits.target[802])

[[  0.   0.   0.  11.  13.   5.   0.   0.]
 [  0.   0.   3.  16.  13.   3.   0.   0.]
 [  0.   0.  10.  16.   2.   0.   0.   0.]
 [  0.   4.  16.  16.  13.   7.   0.   0.]
 [  0.   4.  16.  11.   8.  16.   2.   0.]
 [  0.   0.  15.   8.   0.  15.   6.   0.]
 [  0.   0.   9.  14.   4.  15.   4.   0.]
 [  0.   0.   1.  10.  16.  11.   1.   0.]]
6


In [9]:
digits.images[802].reshape(-1)

array([  0.,   0.,   0.,  11.,  13.,   5.,   0.,   0.,   0.,   0.,   3.,
        16.,  13.,   3.,   0.,   0.,   0.,   0.,  10.,  16.,   2.,   0.,
         0.,   0.,   0.,   4.,  16.,  16.,  13.,   7.,   0.,   0.,   0.,
         4.,  16.,  11.,   8.,  16.,   2.,   0.,   0.,   0.,  15.,   8.,
         0.,  15.,   6.,   0.,   0.,   0.,   9.,  14.,   4.,  15.,   4.,
         0.,   0.,   0.,   1.,  10.,  16.,  11.,   1.,   0.])

In [15]:
digits.images.reshape((len(digits.images), -1)).shape

(1797, 64)

In [5]:
print(digits.target_names)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
images_and_labels = list(zip(digits.images, digits.target))

In [7]:
print(images_and_labels[110])

(array([[  0.,   0.,   0.,  10.,  15.,   0.,   0.,   0.],
       [  0.,   0.,  11.,  15.,   3.,   0.,   0.,   0.],
       [  0.,   7.,  15.,   4.,   0.,   0.,   0.,   0.],
       [  0.,  12.,  11.,   1.,   3.,   8.,   2.,   0.],
       [  0.,   4.,  12.,  15.,  15.,  16.,   9.,   0.],
       [  0.,   0.,   0.,   8.,  16.,   8.,   2.,   0.],
       [  0.,   0.,   0.,  10.,  12.,   0.,   0.,   0.],
       [  0.,   0.,   0.,  12.,   9.,   0.,   0.,   0.]]), 4)


In [8]:
for index, (image, label) in enumerate(images_and_labels[100:105]):
    print('id: {}, img: {}, label: {}'.format(index, image, label))

id: 0, img: [[  0.   0.   0.   2.  13.   0.   0.   0.]
 [  0.   0.   0.   8.  15.   0.   0.   0.]
 [  0.   0.   5.  16.   5.   2.   0.   0.]
 [  0.   0.  15.  12.   1.  16.   4.   0.]
 [  0.   4.  16.   2.   9.  16.   8.   0.]
 [  0.   0.  10.  14.  16.  16.   4.   0.]
 [  0.   0.   0.   0.  13.   8.   0.   0.]
 [  0.   0.   0.   0.  13.   6.   0.   0.]], label: 4
id: 1, img: [[  0.   0.   1.  12.   5.   0.   0.   0.]
 [  0.   0.   9.  16.  14.   3.   0.   0.]
 [  0.   2.  16.  14.  11.  13.   0.   0.]
 [  0.   2.  16.  10.   0.  14.   4.   0.]
 [  0.   4.  16.   0.   0.  12.   4.   0.]
 [  0.   4.  16.   3.   0.  11.  10.   0.]
 [  0.   0.  13.  12.   8.  14.   6.   0.]
 [  0.   0.   3.  10.  16.  12.   1.   0.]], label: 0
id: 2, img: [[  0.   0.  12.  16.  16.   8.   0.   0.]
 [  0.   3.  16.  13.   8.   5.   0.   0.]
 [  0.   2.  16.   3.   0.   0.   0.   0.]
 [  0.   0.  16.  13.   9.   0.   0.   0.]
 [  0.   0.  10.  16.  16.   7.   0.   0.]
 [  0.   0.   0.   1.  10.  13.   0.   

In [9]:
a = np.array([[1,2,3], [4,5,6]])

In [10]:
a.reshape((1, -1))

array([[1, 2, 3, 4, 5, 6]])

In [11]:
n_samples = len(digits.images)
data = digits.images.reshape((n_samples, -1))

In [12]:
print(data[:2])
print(digits.target[102:104])

[[  0.   0.   5.  13.   9.   1.   0.   0.   0.   0.  13.  15.  10.  15.
    5.   0.   0.   3.  15.   2.   0.  11.   8.   0.   0.   4.  12.   0.
    0.   8.   8.   0.   0.   5.   8.   0.   0.   9.   8.   0.   0.   4.
   11.   0.   1.  12.   7.   0.   0.   2.  14.   5.  10.  12.   0.   0.
    0.   0.   6.  13.  10.   0.   0.   0.]
 [  0.   0.   0.  12.  13.   5.   0.   0.   0.   0.   0.  11.  16.   9.
    0.   0.   0.   0.   3.  15.  16.   6.   0.   0.   0.   7.  15.  16.
   16.   2.   0.   0.   0.   0.   1.  16.  16.   3.   0.   0.   0.   0.
    1.  16.  16.   6.   0.   0.   0.   0.   1.  16.  16.   6.   0.   0.
    0.   0.   0.  11.  16.  10.   0.   0.]]
[5 3]
